// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdhveqDoha-uJy_3yWPlYI-QEzwqrEroo',
    appId: '1:655474431388:web:84ec2338757b039a746459',
    messagingSenderId: '655474431388',
    projectId: 'ecomerce-clot-shop',
    authDomain: 'ecomerce-clot-shop.firebaseapp.com',
    storageBucket: 'ecomerce-clot-shop.appspot.com',
    measurementId: 'G-7ZG213K224',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKZ1GNSKYfRTFEZgdSLqpQwtE00MWlZ6s',
    appId: '1:655474431388:android:a10cd04a5b91a4c0746459',
    messagingSenderId: '655474431388',
    projectId: 'ecomerce-clot-shop',
    storageBucket: 'ecomerce-clot-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKePtd5g_xRmZrTyZ1ilztPcrNYwLqwLY',
    appId: '1:655474431388:ios:fdf1c8871a698c9b746459',
    messagingSenderId: '655474431388',
    projectId: 'ecomerce-clot-shop',
    storageBucket: 'ecomerce-clot-shop.appspot.com',
    androidClientId: '655474431388-bkbrsgurauisc9g9rsj9ga9rt8juigo7.apps.googleusercontent.com',
    iosClientId: '655474431388-dd3hdhujk2s590tgnuosegmd4ibbhs72.apps.googleusercontent.com',
    iosBundleId: 'com.example.eClotShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKePtd5g_xRmZrTyZ1ilztPcrNYwLqwLY',
    appId: '1:655474431388:ios:fdf1c8871a698c9b746459',
    messagingSenderId: '655474431388',
    projectId: 'ecomerce-clot-shop',
    storageBucket: 'ecomerce-clot-shop.appspot.com',
    androidClientId: '655474431388-bkbrsgurauisc9g9rsj9ga9rt8juigo7.apps.googleusercontent.com',
    iosClientId: '655474431388-dd3hdhujk2s590tgnuosegmd4ibbhs72.apps.googleusercontent.com',
    iosBundleId: 'com.example.eClotShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdhveqDoha-uJy_3yWPlYI-QEzwqrEroo',
    appId: '1:655474431388:web:056fb998621c0819746459',
    messagingSenderId: '655474431388',
    projectId: 'ecomerce-clot-shop',
    authDomain: 'ecomerce-clot-shop.firebaseapp.com',
    storageBucket: 'ecomerce-clot-shop.appspot.com',
    measurementId: 'G-CRM0EYTQHW',
  );
}
